from __future__ import annotations

import ast
import json
from pathlib import Path

from app.models.schemas import AnalysisResult, GeneratedFile, GenerationResult, ModuleSummary, PlanResult
from app.services.openai_test_writer import OpenAITestWriter
from app.utils.files import reset_generated_tests_dir


class TestGeneratorService:
    def __init__(self) -> None:
        self.openai_writer = OpenAITestWriter()

    def generate(
        self,
        repository_path: str,
        run_dir: Path,
        analysis: AnalysisResult,
        plan: PlanResult,
        mode: str = "balanced",
        model: str | None = None,
    ) -> GenerationResult:
        generated_dir = reset_generated_tests_dir(run_dir)
        repo_path = Path(repository_path).resolve()
        files: list[GeneratedFile] = []
        provider = self.openai_writer.provider_name
        selected_model = self.openai_writer.resolve_model(model) if self.openai_writer.enabled else None

        if "python" in analysis.detected_languages:
            files.append(self._write_python_conftest(generated_dir, repo_path))

        for module in analysis.modules:
            target_path = self._target_path_for_module(generated_dir, module)
            test_content = self._build_test_for_module(module, mode, repo_path, selected_model)
            target_path.write_text(test_content, encoding="utf-8")
            files.append(
                GeneratedFile(
                    file_path=str(target_path),
                    strategy=f"{mode} {provider} autogenerated tests for {module.module_import}",
                )
            )

        language_summary = ", ".join(language.title() for language in analysis.detected_languages) or "Unknown"
        return GenerationResult(
            generated_files=files,
            mode="safe" if mode == "safe" else "balanced",
            provider=provider,
            model=selected_model,
            summary=f"Generated {len(files)} test files in {mode} mode using {provider} generation for {language_summary} sources.",
        )

    def _write_python_conftest(self, generated_dir: Path, repo_path: Path) -> GeneratedFile:
        conftest_path = generated_dir / "conftest.py"
        conftest_path.write_text(
            "import sys\n"
            "from pathlib import Path\n\n"
            f"REPO_ROOT = Path(r'{repo_path}')\n"
            "if str(REPO_ROOT) not in sys.path:\n"
            "    sys.path.insert(0, str(REPO_ROOT))\n",
            encoding="utf-8",
        )
        return GeneratedFile(file_path=str(conftest_path), strategy="repository import path bootstrap")

    def _target_path_for_module(self, generated_dir: Path, module: ModuleSummary) -> Path:
        slug = module.module_import.replace(".", "_").replace("/", "_").replace("\\", "_")
        return generated_dir / f"test_{slug}.py"

    def _build_test_for_module(self, module: ModuleSummary, mode: str, repo_path: Path, model: str | None = None) -> str:
        if self.openai_writer.enabled and module.language == "python":
            generated = self.openai_writer.generate_module_test(module, mode, repo_path, model)
            if generated and self._looks_like_test_module(generated, module.language):
                return generated

        if module.language == "python":
            return self._build_python_test_module(module.module_import, module.functions, mode)
        return self._build_source_smoke_test_module(module, mode)

    def _build_python_test_module(self, module_import: str, functions: list, mode: str) -> str:
        lines = [
            "import importlib",
            "import pytest",
            "",
            f"MODULE_NAME = '{module_import}'",
            "",
            "",
            "def test_module_imports():",
            "    module = importlib.import_module(MODULE_NAME)",
            "    assert module is not None",
        ]

        if functions:
            lines.extend(
                [
                    "",
                    "",
                    "@pytest.mark.parametrize('function_name', [",
                ]
            )
            for fn in functions:
                lines.append(f"    '{fn.name}',")
            lines.extend(
                [
                    "])",
                    "def test_functions_exist(function_name):",
                    "    module = importlib.import_module(MODULE_NAME)",
                    "    assert hasattr(module, function_name)",
                ]
            )

        inferred_cases = [(fn.name, case) for fn in functions for case in fn.inferred_cases]
        if inferred_cases:
            lines.extend(
                [
                    "",
                    "",
                    "@pytest.mark.parametrize(('function_name', 'arguments', 'expected_value'), [",
                ]
            )
            for function_name, case in inferred_cases:
                lines.append(
                    f"    ('{function_name}', [{', '.join(case.arguments)}], {case.expected_expression}),  # {case.description}"
                )
            lines.extend(
                [
                    "])",
                    "def test_inferred_function_behavior(function_name, arguments, expected_value):",
                    "    module = importlib.import_module(MODULE_NAME)",
                    "    function = getattr(module, function_name)",
                    "    assert function(*arguments) == expected_value",
                ]
            )

        zero_arg_functions = [fn.name for fn in functions if fn.required_arg_count == 0]
        if mode == "balanced" and zero_arg_functions:
            lines.extend(
                [
                    "",
                    "",
                    "@pytest.mark.parametrize('function_name', [",
                ]
            )
            for function_name in zero_arg_functions:
                lines.append(f"    '{function_name}',")
            lines.extend(
                [
                    "])",
                    "def test_zero_arg_functions_execute(function_name):",
                    "    module = importlib.import_module(MODULE_NAME)",
                    "    function = getattr(module, function_name)",
                    "    assert callable(function)",
                    "    function()",
                ]
            )

        return "\n".join(lines) + "\n"

    def _build_source_smoke_test_module(self, module: ModuleSummary, mode: str) -> str:
        source_path = json.dumps(str(Path(module.file_path).resolve()))
        source_name = Path(module.file_path).name
        lines = [
            "from pathlib import Path",
            "import re",
            "",
            f"SOURCE_PATH = Path({source_path})",
            f"EXPECTED_SUFFIX = {json.dumps(Path(module.file_path).suffix)}",
            "",
            "",
            "def test_source_file_exists():",
            "    assert SOURCE_PATH.exists()",
            "    assert SOURCE_PATH.is_file()",
            "",
            "",
            "def test_source_file_is_not_empty():",
            "    content = SOURCE_PATH.read_text(encoding='utf-8', errors='ignore')",
            "    assert content.strip()",
            "",
            "",
            "def test_source_file_suffix_matches_expected():",
            "    assert SOURCE_PATH.suffix == EXPECTED_SUFFIX",
        ]

        for function in module.functions:
            lines.extend(
                [
                    "",
                    f"def test_source_mentions_{function.name}():",
                    "    content = SOURCE_PATH.read_text(encoding='utf-8', errors='ignore')",
                    f"    assert re.search(r'\\b{function.name}\\b', content)",
                ]
            )

        if mode == "balanced":
            lines.extend(
                [
                    "",
                    "",
                    "def test_source_path_is_stable():",
                    f"    assert SOURCE_PATH.name == {json.dumps(source_name)}",
                ]
            )

        return "\n".join(lines) + "\n"

    def _looks_like_test_module(self, content: str, language: str) -> bool:
        if language in {"python", "javascript", "typescript", "generic"}:
            try:
                ast.parse(content)
            except SyntaxError:
                return False
            return "def test_" in content
