from __future__ import annotations

import ast
import json
from pathlib import Path

from app.models.schemas import AnalysisResult, GeneratedFile, GenerationResult, ModuleSummary, PlanResult
from app.services.openai_test_writer import OpenAITestWriter
from app.utils.files import reset_generated_tests_dir


class TestGeneratorService:
    def __init__(self) -> None:
        self.openai_writer = OpenAITestWriter()

    def generate(
        self,
        repository_path: str,
        run_dir: Path,
        analysis: AnalysisResult,
        plan: PlanResult,
        mode: str = "balanced",
    ) -> GenerationResult:
        generated_dir = reset_generated_tests_dir(run_dir)
        repo_path = Path(repository_path).resolve()
        files: list[GeneratedFile] = []
        provider = self.openai_writer.provider_name
        model = self.openai_writer.model if self.openai_writer.enabled else None

        if "python" in analysis.detected_languages:
            files.append(self._write_python_conftest(generated_dir, repo_path))

        for module in analysis.modules:
            if not module.functions and mode == "safe":
                continue

            target_path = self._target_path_for_module(generated_dir, module)
            test_content = self._build_test_for_module(module, mode, repo_path)
            target_path.write_text(test_content, encoding="utf-8")
            files.append(
                GeneratedFile(
                    file_path=str(target_path),
                    strategy=f"{mode} {provider} autogenerated tests for {module.module_import}",
                )
            )

        language_summary = ", ".join(language.title() for language in analysis.detected_languages) or "Unknown"
        return GenerationResult(
            generated_files=files,
            mode="safe" if mode == "safe" else "balanced",
            provider=provider,
            model=model,
            summary=f"Generated {len(files)} test files in {mode} mode using {provider} generation for {language_summary} sources.",
        )

    def _write_python_conftest(self, generated_dir: Path, repo_path: Path) -> GeneratedFile:
        conftest_path = generated_dir / "conftest.py"
        conftest_path.write_text(
            "import sys\n"
            "from pathlib import Path\n\n"
            f"REPO_ROOT = Path(r'{repo_path}')\n"
            "if str(REPO_ROOT) not in sys.path:\n"
            "    sys.path.insert(0, str(REPO_ROOT))\n",
            encoding="utf-8",
        )
        return GeneratedFile(file_path=str(conftest_path), strategy="repository import path bootstrap")

    def _target_path_for_module(self, generated_dir: Path, module: ModuleSummary) -> Path:
        slug = module.module_import.replace(".", "_").replace("/", "_").replace("\\", "_")
        if module.language == "python":
            return generated_dir / f"test_{slug}.py"
        if module.language == "typescript":
            return generated_dir / f"{slug}.test.ts"
        return generated_dir / f"{slug}.test.cjs"

    def _build_test_for_module(self, module: ModuleSummary, mode: str, repo_path: Path) -> str:
        if self.openai_writer.enabled:
            generated = self.openai_writer.generate_module_test(module, mode, repo_path)
            if generated and self._looks_like_test_module(generated, module.language):
                return generated

        if module.language == "python":
            return self._build_python_test_module(module.module_import, module.functions, mode)
        if module.language == "typescript":
            return self._build_typescript_test_module(module, mode)
        return self._build_javascript_test_module(module, mode)

    def _build_python_test_module(self, module_import: str, functions: list, mode: str) -> str:
        lines = [
            "import importlib",
            "import pytest",
            "",
            f"MODULE_NAME = '{module_import}'",
            "",
            "",
            "def test_module_imports():",
            "    module = importlib.import_module(MODULE_NAME)",
            "    assert module is not None",
        ]

        if functions:
            lines.extend(
                [
                    "",
                    "",
                    "@pytest.mark.parametrize('function_name', [",
                ]
            )
            for fn in functions:
                lines.append(f"    '{fn.name}',")
            lines.extend(
                [
                    "])",
                    "def test_functions_exist(function_name):",
                    "    module = importlib.import_module(MODULE_NAME)",
                    "    assert hasattr(module, function_name)",
                ]
            )

        inferred_cases = [(fn.name, case) for fn in functions for case in fn.inferred_cases]
        if inferred_cases:
            lines.extend(
                [
                    "",
                    "",
                    "@pytest.mark.parametrize(('function_name', 'arguments', 'expected_value'), [",
                ]
            )
            for function_name, case in inferred_cases:
                lines.append(
                    f"    ('{function_name}', [{', '.join(case.arguments)}], {case.expected_expression}),  # {case.description}"
                )
            lines.extend(
                [
                    "])",
                    "def test_inferred_function_behavior(function_name, arguments, expected_value):",
                    "    module = importlib.import_module(MODULE_NAME)",
                    "    function = getattr(module, function_name)",
                    "    assert function(*arguments) == expected_value",
                ]
            )

        zero_arg_functions = [fn.name for fn in functions if fn.required_arg_count == 0]
        if mode == "balanced" and zero_arg_functions:
            lines.extend(
                [
                    "",
                    "",
                    "@pytest.mark.parametrize('function_name', [",
                ]
            )
            for function_name in zero_arg_functions:
                lines.append(f"    '{function_name}',")
            lines.extend(
                [
                    "])",
                    "def test_zero_arg_functions_execute(function_name):",
                    "    module = importlib.import_module(MODULE_NAME)",
                    "    function = getattr(module, function_name)",
                    "    assert callable(function)",
                    "    function()",
                ]
            )

        return "\n".join(lines) + "\n"

    def _build_javascript_test_module(self, module: ModuleSummary, mode: str) -> str:
        source_path = json.dumps(str(Path(module.file_path).resolve()))
        zero_arg_functions = [fn.name for fn in module.functions if fn.required_arg_count == 0]
        lines = [
            "const test = require('node:test');",
            "const assert = require('node:assert/strict');",
            "const { pathToFileURL } = require('node:url');",
            "",
            f"const SOURCE_PATH = {source_path};",
            "",
            "async function loadModule() {",
            "  return import(pathToFileURL(SOURCE_PATH).href);",
            "}",
            "",
            "function getExport(moduleNamespace, name) {",
            "  if (moduleNamespace && Object.prototype.hasOwnProperty.call(moduleNamespace, name)) {",
            "    return moduleNamespace[name];",
            "  }",
            "  if (moduleNamespace?.default && Object.prototype.hasOwnProperty.call(moduleNamespace.default, name)) {",
            "    return moduleNamespace.default[name];",
            "  }",
            "  return undefined;",
            "}",
            "",
            "test('module loads', async () => {",
            "  const moduleNamespace = await loadModule();",
            "  assert.ok(moduleNamespace);",
            "});",
        ]

        for function in module.functions:
            lines.extend(
                [
                    "",
                    f"test('exports {function.name}', async () => {{",
                    "  const moduleNamespace = await loadModule();",
                    f"  const exported = getExport(moduleNamespace, '{function.name}');",
                    "  assert.equal(typeof exported, 'function');",
                    "});",
                ]
            )

        if mode == "balanced":
            for function_name in zero_arg_functions:
                lines.extend(
                    [
                        "",
                        f"test('executes {function_name} without arguments', async () => {{",
                        "  const moduleNamespace = await loadModule();",
                        f"  const exported = getExport(moduleNamespace, '{function_name}');",
                        "  assert.equal(typeof exported, 'function');",
                        "  await Promise.resolve(exported());",
                        "});",
                    ]
                )

        return "\n".join(lines) + "\n"

    def _build_typescript_test_module(self, module: ModuleSummary, mode: str) -> str:
        source_path = json.dumps(str(Path(module.file_path).resolve())).replace("\\\\", "/")
        zero_arg_functions = [fn.name for fn in module.functions if fn.required_arg_count == 0]
        lines = [
            "import test from 'node:test';",
            "import assert from 'node:assert/strict';",
            "import { pathToFileURL } from 'node:url';",
            "",
            f"const SOURCE_PATH = {source_path};",
            "",
            "async function loadModule() {",
            "  return import(pathToFileURL(SOURCE_PATH).href);",
            "}",
            "",
            "function getExport(moduleNamespace: Record<string, unknown>, name: string) {",
            "  if (name in moduleNamespace) {",
            "    return moduleNamespace[name];",
            "  }",
            "  const defaultExport = moduleNamespace.default as Record<string, unknown> | undefined;",
            "  if (defaultExport && name in defaultExport) {",
            "    return defaultExport[name];",
            "  }",
            "  return undefined;",
            "}",
            "",
            "test('module loads', async () => {",
            "  const moduleNamespace = await loadModule();",
            "  assert.ok(moduleNamespace);",
            "});",
        ]

        for function in module.functions:
            lines.extend(
                [
                    "",
                    f"test('exports {function.name}', async () => {{",
                    "  const moduleNamespace = await loadModule();",
                    f"  const exported = getExport(moduleNamespace as Record<string, unknown>, '{function.name}');",
                    "  assert.equal(typeof exported, 'function');",
                    "});",
                ]
            )

        if mode == "balanced":
            for function_name in zero_arg_functions:
                lines.extend(
                    [
                        "",
                        f"test('executes {function_name} without arguments', async () => {{",
                        "  const moduleNamespace = await loadModule();",
                        f"  const exported = getExport(moduleNamespace as Record<string, unknown>, '{function_name}') as (() => unknown) | undefined;",
                        "  assert.equal(typeof exported, 'function');",
                        "  await Promise.resolve(exported && exported());",
                        "});",
                    ]
                )

        return "\n".join(lines) + "\n"

    def _looks_like_test_module(self, content: str, language: str) -> bool:
        if language == "python":
            try:
                ast.parse(content)
            except SyntaxError:
                return False
            return "def test_" in content

        if language == "typescript":
            return "test(" in content and "SOURCE_PATH" in content

        return "test(" in content and "SOURCE_PATH" in content
