from __future__ import annotations

from pathlib import Path

from app.models.schemas import AnalysisResult, GeneratedFile, GenerationResult, PlanResult
from app.utils.files import reset_generated_tests_dir


class TestGeneratorService:
    def generate(
        self,
        repository_path: str,
        run_dir: Path,
        analysis: AnalysisResult,
        plan: PlanResult,
        mode: str = "balanced",
    ) -> GenerationResult:
        generated_dir = reset_generated_tests_dir(run_dir)
        repo_path = Path(repository_path).resolve()
        files = [self._write_conftest(generated_dir, repo_path)]

        for module in analysis.modules:
            if not module.functions and mode == "safe":
                continue
            target_path = generated_dir / f"test_{module.module_import.replace('.', '_')}.py"
            target_path.write_text(self._build_test_module(module.module_import, module.functions, mode), encoding="utf-8")
            files.append(
                GeneratedFile(
                    file_path=str(target_path),
                    strategy=f"{mode} autogenerated tests for {module.module_import}",
                )
            )

        return GenerationResult(
            generated_files=files,
            mode="safe" if mode == "safe" else "balanced",
            summary=f"Generated {len(files)} pytest files in {mode} mode.",
        )

    def _write_conftest(self, generated_dir: Path, repo_path: Path) -> GeneratedFile:
        conftest_path = generated_dir / "conftest.py"
        conftest_path.write_text(
            "import sys\n"
            "from pathlib import Path\n\n"
            f"REPO_ROOT = Path(r'{repo_path}')\n"
            "if str(REPO_ROOT) not in sys.path:\n"
            "    sys.path.insert(0, str(REPO_ROOT))\n",
            encoding="utf-8",
        )
        return GeneratedFile(file_path=str(conftest_path), strategy="repository import path bootstrap")

    def _build_test_module(self, module_import: str, functions: list, mode: str) -> str:
        lines = [
            "import importlib",
            "import pytest",
            "",
            f"MODULE_NAME = '{module_import}'",
            "",
            "",
            "def test_module_imports():",
            "    module = importlib.import_module(MODULE_NAME)",
            "    assert module is not None",
        ]

        if functions:
            lines.extend(
                [
                    "",
                    "",
                    "@pytest.mark.parametrize('function_name', [",
                ]
            )
            for fn in functions:
                lines.append(f"    '{fn.name}',")
            lines.extend(
                [
                    "])",
                    "def test_functions_exist(function_name):",
                    "    module = importlib.import_module(MODULE_NAME)",
                    "    assert hasattr(module, function_name)",
                ]
            )

        zero_arg_functions = [fn.name for fn in functions if fn.arg_count == 0]
        if mode == "balanced" and zero_arg_functions:
            lines.extend(
                [
                    "",
                    "",
                    "@pytest.mark.parametrize('function_name', [",
                ]
            )
            for function_name in zero_arg_functions:
                lines.append(f"    '{function_name}',")
            lines.extend(
                [
                    "])",
                    "def test_zero_arg_functions_execute(function_name):",
                    "    module = importlib.import_module(MODULE_NAME)",
                    "    function = getattr(module, function_name)",
                    "    assert callable(function)",
                    "    function()",
                ]
            )

        return "\n".join(lines) + "\n"
