apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testdebugger-ingress
  namespace: testdebugger
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: testdebugger.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testdebugger-app
                port:
                  number: 80
