apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: testdebugger
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: change-me-root-password
  MYSQL_DATABASE: testdebugger
  MYSQL_USER: testdebugger
  MYSQL_PASSWORD: change-me-app-password
